[build]
  command   = "npm run build"
  publish   = "dist"
  environment = { NODE_VERSION = "18" }   # vite 5 LTS target[8][88]

# SPA fallback ─ ensures any deep link loads the app
[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200

# Manifest MIME type (fails Lighthouse without this)[97]
[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"

# Aggressive immutable cache for hashed assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    cache-control = '''
    max-age=31536000,
    immutable'''

# Looser cache for HTML & SW so updates propagate[6][18]
[[headers]]
  for = "/sw.js"
  [headers.values]
    cache-control = "no-cache"
    
